# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.


# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

# NOTE: the packages commented are used for local development, and not needed for deployment

name: uplab
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.6
- conda-forge::spacy
- pip:
  # - azureml-defaults==1.0.15
  # German Spacy NLP Model
  # - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.0.0/de_core_news_sm-2.0.0.tar.gz
  - openpyxl 
- numpy
- pandas
- scikit-learn
- nltk
- nb_conda
- matplotlib
- seaborn