# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.


# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

# NOTE: the packages commented are used for local development, and not needed for deployment

name: uplab
dependencies:
- python=3.6.6
- conda-forge::spacy=2.1.3
- pip:
  # German Spacy NLP Model #TODO: if used in docker, update
  - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz#egg=de_core_news_sm
  - imblearn
  - openpyxl 
  - pyyaml
  - xlrd
- numpy
- pandas
- scikit-learn
- nltk
- nb_conda
- matplotlib
- seaborn