data:
    dir: C:/Users/makayser/Desktop/ul_label/tal/
    source: raw_v1.txt
    cols: ['text_b','label','tag']
    extras: ['entity', 'entity_type', 'comment', 'text']
    target_column: target
    text_column: text

parameters:
    task: cat
    language: de
    labelers: 3
    quality: 1
    estimate_clusters: True