data:
    dir: ../
    source: input.txt
    cols: ['text','label']
    extras: []
    target_column: label
    text_column: text

parameters:
    task: cat
    language: de
    labelers: 3
    min_split_size: 200
    max_split_size : False
    quality: 3
    estimate_clusters: True
    quality_size: 0.1
    overlap_size: 0.1