data:
    dir: ../data/news_de/ 
    source: input.txt
    cols: ['text','label']
    extras: []
    target_column: target
    text_column: text

parameters:
    task: cat
    language: de
    labelers: 2
    quality: 1
    estimate_clusters: True
    quality_size: 0.1
    overlap_size: 0.1
    min_split_size: 0
    max_split_size : 100